# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PatchRepo < Formula
  desc "Manage custom changes to cloned git repos without maintaining forks"
  homepage "https://github.com/cchitsiang/patch-repo"
  version "0.4.0"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cchitsiang/patch-repo/releases/download/v0.4.0/patch-repo_0.4.0_darwin_amd64.tar.gz"
      sha256 "ccf0333d3d69328419e584dc18ab4d31b596ca452d1c423f340c787e1f50e373"

      define_method(:install) do
        bin.install "patch-repo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cchitsiang/patch-repo/releases/download/v0.4.0/patch-repo_0.4.0_darwin_arm64.tar.gz"
      sha256 "4aed9d11dcc3890abde37379bfc7a5981b870cf331d724bf3897b31379b1da9b"

      define_method(:install) do
        bin.install "patch-repo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cchitsiang/patch-repo/releases/download/v0.4.0/patch-repo_0.4.0_linux_amd64.tar.gz"
      sha256 "a9dbdb291c73d64c88c98d508ff171e2e1b4d386e131402bffbb4189b31a5362"
      define_method(:install) do
        bin.install "patch-repo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cchitsiang/patch-repo/releases/download/v0.4.0/patch-repo_0.4.0_linux_arm64.tar.gz"
      sha256 "5e9bdf4c1154f74b21a7e45a5120c8c0fcffc2959cc159b558d2583ebc7fdd77"
      define_method(:install) do
        bin.install "patch-repo"
      end
    end
  end

  test do
    system "#{bin}/patch-repo", "--help"
  end
end
