# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PatchRepo < Formula
  desc "Manage custom changes to cloned git repos without maintaining forks"
  homepage "https://github.com/cchitsiang/patch-repo"
  version "0.2.0"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cchitsiang/patch-repo/releases/download/v0.2.0/patch-repo_0.2.0_darwin_amd64.tar.gz"
      sha256 "4b055bf7151fb1266eeb7432c16036c5d132b1fcd26dec7cf0fab2b1b574eefb"

      define_method(:install) do
        bin.install "patch-repo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cchitsiang/patch-repo/releases/download/v0.2.0/patch-repo_0.2.0_darwin_arm64.tar.gz"
      sha256 "397c686c05c558a13ae9d4ada8be9e04936dbfcf1f6b826ed33fa89dfbc449ae"

      define_method(:install) do
        bin.install "patch-repo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cchitsiang/patch-repo/releases/download/v0.2.0/patch-repo_0.2.0_linux_amd64.tar.gz"
      sha256 "71be979835ae8356f7bbf3cf07b92ff3f113f28385ec79c728ee7227295524d6"
      define_method(:install) do
        bin.install "patch-repo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cchitsiang/patch-repo/releases/download/v0.2.0/patch-repo_0.2.0_linux_arm64.tar.gz"
      sha256 "a91000852ad925cbdba141d07f4e8eb9afe6bf0fe02e6e19cf10df27629715a2"
      define_method(:install) do
        bin.install "patch-repo"
      end
    end
  end

  test do
    system "#{bin}/patch-repo", "--help"
  end
end
